// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package pbmessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogMessage struct {
	DeployId             int32    `protobuf:"varint,1,opt,name=deploy_id,json=deployId,proto3" json:"deploy_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	CmdStatus            string   `protobuf:"bytes,4,opt,name=cmd_status,json=cmdStatus,proto3" json:"cmd_status,omitempty"`
	CmdType              string   `protobuf:"bytes,5,opt,name=cmd_type,json=cmdType,proto3" json:"cmd_type,omitempty"`
	DeployStatus         string   `protobuf:"bytes,6,opt,name=deploy_status,json=deployStatus,proto3" json:"deploy_status,omitempty"`
	Hosts                string   `protobuf:"bytes,7,opt,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_a0ab1c583f7fb2f6, []int{0}
}
func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (dst *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(dst, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetDeployId() int32 {
	if m != nil {
		return m.DeployId
	}
	return 0
}

func (m *LogMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogMessage) GetCmdStatus() string {
	if m != nil {
		return m.CmdStatus
	}
	return ""
}

func (m *LogMessage) GetCmdType() string {
	if m != nil {
		return m.CmdType
	}
	return ""
}

func (m *LogMessage) GetDeployStatus() string {
	if m != nil {
		return m.DeployStatus
	}
	return ""
}

func (m *LogMessage) GetHosts() string {
	if m != nil {
		return m.Hosts
	}
	return ""
}

func init() {
	proto.RegisterType((*LogMessage)(nil), "pbmessage.LogMessage")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_log_a0ab1c583f7fb2f6) }

var fileDescriptor_log_a0ab1c583f7fb2f6 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xcd, 0xaa, 0xc2, 0x30,
	0x10, 0x85, 0xc9, 0xed, 0x6f, 0x86, 0xeb, 0x66, 0x70, 0x31, 0x22, 0x42, 0xd1, 0x4d, 0x57, 0x6e,
	0x7c, 0x0a, 0x41, 0x37, 0xd5, 0x7d, 0x69, 0x9b, 0x50, 0x0b, 0x0d, 0x09, 0x26, 0x2e, 0xfa, 0x8e,
	0x3e, 0x94, 0x98, 0xc4, 0xdd, 0x9c, 0xf3, 0xf1, 0x0d, 0x33, 0xc0, 0x67, 0x3d, 0x1e, 0xcd, 0x53,
	0x3b, 0x8d, 0xdc, 0xf4, 0x4a, 0x5a, 0xdb, 0x8d, 0x72, 0xff, 0x66, 0x00, 0x17, 0x3d, 0x5e, 0x43,
	0xc4, 0x2d, 0x70, 0x21, 0xcd, 0xac, 0x97, 0x76, 0x12, 0xc4, 0x2a, 0x56, 0x67, 0x4d, 0x19, 0x8a,
	0xb3, 0x40, 0x82, 0x22, 0x6a, 0xf4, 0x57, 0xb1, 0x9a, 0x37, 0xbf, 0x88, 0x08, 0xa9, 0x9b, 0x94,
	0xa4, 0xa4, 0x62, 0x75, 0xd2, 0xf8, 0x19, 0x77, 0x00, 0x83, 0x12, 0xad, 0x75, 0x9d, 0x7b, 0x59,
	0x4a, 0xbd, 0xc0, 0x07, 0x25, 0x6e, 0xbe, 0xc0, 0x0d, 0x94, 0x5f, 0xec, 0x16, 0x23, 0x29, 0x0b,
	0xdb, 0x06, 0x25, 0xee, 0x8b, 0x91, 0x78, 0x80, 0x55, 0x3c, 0x22, 0xca, 0xb9, 0xe7, 0xff, 0xa1,
	0x8c, 0xfe, 0x1a, 0xb2, 0x87, 0xb6, 0xce, 0x52, 0xe1, 0x61, 0x08, 0x7d, 0xee, 0x1f, 0x3c, 0x7d,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x8d, 0x00, 0xf5, 0xed, 0x00, 0x00, 0x00,
}
